kind: pipeline
type: docker
name: build-arm64

when:
  event:
    - manual
    - push

environment:
  REPO_DOCKERHUB: docker.io/qyg2297248353/ammds-dev
  REPO_GHCR: ghcr.io/qyg2297248353/ammds-dev
  REF_NAME: dev-arm64

steps:
  - name: clone-source
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GIT_LFS_SKIP_SMUDGE: "1"
    commands:
      - apk add --no-cache git-lfs
      - git lfs install --skip-smudge
      - git clone https://x-access-token:${GITHUB_TOKEN}@github.com/QYG2297248353/AMMDS.git source
      - cd source
      - git lfs pull --exclude="*"

  - name: setup-qemu
    image: tonistiigi/binfmt
    privileged: true
    commands:
      - binfmt --install arm64

  - name: docker-login
    image: docker:26-cli
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_TOKEN:
        from_secret: DOCKERHUB_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u QYG2297248353 --password-stdin

  - name: build-arm64
    image: docker:26-cli
    privileged: true
    commands:
      - docker buildx create --use --name ammds || docker buildx use ammds
      - docker buildx inspect --bootstrap
      - |
        docker buildx build \
          --platform linux/arm64 \
          -f source/Dockerfile \
          -t ${REPO_DOCKERHUB}:${REF_NAME}-arm64 \
          -t ${REPO_GHCR}:${REF_NAME}-arm64 \
          --push \
          source

volumes:
  - name: dockersock
    path: /var/run/docker.sock
