name: 'Bug 反馈'
description: '功能异常或出错的情况'
title: '[Bug] '
assignees: QYG2297248353
labels: Bug - 程序错误
body:
  - type: markdown
    attributes:
      value: |
        感谢您花费时间反馈问题，使用更加详细问题描述，我们便可更快的定位解决问题。感谢您对AMMDS的支持！
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: 我已阅读 [官方文档](https://ammds.lifebus.top/guide/qa/) 的常见问题
          required: true
        - label: 我已检索 `Issues` 并且未发现相似问题
          required: true
        - label: 我已确认 `安装版本` 为最新版本
          required: true
  - type: textarea
    id: repro
    attributes:
      label: 问题描述
      description: "详细描述您遇到的问题"
      placeholder: |
        1. 发生的功能模块
        2. 异常的截图
        3. 详细的问题的描述
        ...
      value: ""
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 日志记录
      description: "(可选)粘贴运行日志"
      placeholder: |
        日志文件内容
        ...
      value: ""
      render: bash
    validations:
      required: false
