name: build-backend-base

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile-BackBase'

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout AMMDS source
        uses: actions/checkout@v4
        with:
          repository: QYG2297248353/AMMDS
          token: ${{ secrets.GITHUBTOKEN }}
          path: ammds-source

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to registries
        uses: docker/login-action@v3
        with:
          registries: |
            docker.io
            ghcr.io
          username: |
            ${{ secrets.DOCKERHUB_USERNAME }}
            ${{ github.actor }}
          password: |
            ${{ secrets.DOCKERHUB_TOKEN }}
            ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend builder base image
        uses: docker/build-push-action@v5
        with:
          context: ammds-source
          file: ammds-source/Dockerfile-BackBase
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            qyg2297248353/ammds-backend-builder-base:latest
            ghcr.io/qyg2297248353/ammds-backend-builder-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
