name: build-backend-base

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile-BackBase'

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this workflow repo
        uses: actions/checkout@v3

      - name: Clone AMMDS source
        run: |
          git clone https://x-access-token:${{ secrets.GITHUBTOKEN }}@github.com/QYG2297248353/AMMDS.git ammds-source

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Build and push backend builder base image
        uses: docker/build-push-action@v4
        with:
          context: ./ammds-source
          file: ./ammds-source/Dockerfile.backend-base
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            qyg2297248353/ammds-backend-builder-base:latest
            ghcr.io/qyg2297248353/ammds-backend-builder-base:latest
